### ISSUE TITLE
Test error - HAR_TestSearchHAR::testPhases

### ISSUE THREAD

**Issue by gitgrimbo** [janodvarko/harviewer#16]
#### Environment

Selenium server v2.45.0, with Core v2.45.0. Built from revision 5017cb8.
Firefox 37.0.2 and Chrome 43.0.2357.81 m.

#### Outcome

The keys presses do not appear in the input box:

````
        $this->keyPress("css=.tabDOMBody .searchInput", "f");
        $this->keyPress("css=.tabDOMBody .searchInput", "i");
        $this->keyPress("css=.tabDOMBody .searchInput", "r");
        $this->keyPress("css=.tabDOMBody .searchInput", "e");
        $this->keyDown("css=.tabDOMBody .searchInput", "\\13");
````

#### Logs

````
PHPUnit 4.3.5 by Sebastian Bergmann.


HAR Tests::setUp()E
testSearchHAR.php
HAR Tests::tearDown()

Time: 42.38 seconds, Memory: 6.25Mb

There was 1 error:

1) HAR_TestSearchHAR::testPhases

Invalid response while accessing the Selenium Server at 'http://192.168.1.80:4444/selenium-server/driver/': Timed out after 10000ms

Caused by
exception 'RuntimeException' with message 'Invalid response while accessing the Selenium Server at 'http://192.168.1.80:4444/selenium-server/driver/': Timed out after 10000ms' in /home/build/.composer/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Sele
niumTestCase/Driver.php:1066
Stack trace:
#0 /home/build/.composer/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/SeleniumTestCase/Driver.php(983): PHPUnit_Extensions_SeleniumTestCase_Driver->doCommand('waitForConditio...', Array)
#1 [internal function]: PHPUnit_Extensions_SeleniumTestCase_Driver->__call('waitForConditio...', Array)
#2 [internal function]: PHPUnit_Extensions_SeleniumTestCase_Driver->waitForCondition('selenium.browse...', 10000)
#3 /home/build/.composer/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/SeleniumTestCase.php(869): call_user_func_array(Array, Array)
#4 /code/selenium/tests/testSearchHAR.php(36): PHPUnit_Extensions_SeleniumTestCase->__call('waitForConditio...', Array)
#5 /code/selenium/tests/testSearchHAR.php(36): HAR_TestSearchHAR->waitForCondition('selenium.browse...', 10000)
#6 [internal function]: HAR_TestSearchHAR->testPhases()
#7 /home/build/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php(905): ReflectionMethod->invokeArgs(Object(HAR_TestSearchHAR), Array)
#8 /home/build/.composer/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/SeleniumTestCase.php(786): PHPUnit_Framework_TestCase->runTest()
#9 /home/build/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php(775): PHPUnit_Extensions_SeleniumTestCase->runTest()
#10 /home/build/.composer/vendor/phpunit/phpunit/src/Framework/TestResult.php(643): PHPUnit_Framework_TestCase->runBare()
#11 /home/build/.composer/vendor/phpunit/phpunit/src/Framework/TestCase.php(711): PHPUnit_Framework_TestResult->run(Object(HAR_TestSearchHAR))
#12 /home/build/.composer/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/SeleniumTestCase.php(648): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#13 /home/build/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): PHPUnit_Extensions_SeleniumTestCase->run(Object(PHPUnit_Framework_TestResult))
#14 /home/build/.composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php(751): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#15 /home/build/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(423): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#16 /home/build/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(AllTests), Array)
#17 /home/build/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(138): PHPUnit_TextUI_Command->run(Array, true)
#18 /home/build/.composer/vendor/phpunit/phpunit/phpunit(56): PHPUnit_TextUI_Command::main()
#19 {main}
FAILURES!
Tests: 1, Assertions: 1, Errors: 1.
````

**Comment by gitgrimbo** [comment]
Closing as tests have been ported to JavaScript/Intern, and the PHP tests are no longer being maintained.
